### ISSUE TITLE
Analysis patch - Implementation of new filters and redesign

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#189]
## Issue
Right now we dont have filters on individual columns, only a general filter. We need to implement individual filter on columns. 

## Filters
We would like have following filters:

- [x] Status [Checkbox]
- [x] Paid month [Multi selector dropdown]
- [x] Category [Multi selector dropdown]
- [x] Customer [Multi selector dropdown]
- [x] Project [Multi selector dropdown]
- [x] Date [Datepicker] (Should be in a range) 
- [x] startTime  [No filter (?)] (Do we need filter for this one?)
- [x] endTime  [No filter (?)] (Do we need filter for this one?)
- [x] Comment [A string filter]
- [x] Worker [Multi selector dropdown for all workers]

## Discussion
The filters could be placed in table-header like this example: 
https://stackoverflow.com/questions/52959195/bootstrap-vue-b-table-with-filter-in-header

**Comment by astyltsvig** [comment]
Resolved and close
